pr:
  autoCancel: true
  branches:
    include:
      - master
      - develop-*

variables:
- group: Codecov
- name: grayskull_deps
  value: pytest pytest-azurepipelines pytest-xdist pytest-cov pytest-forked requests ruamel.yaml codecov ruamel.yaml.jinja2 "coverage<5.0" stdlib-list pip setuptools mock fuzzywuzzy git colorama progressbar2

jobs:
  - job:
    displayName: Linux
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        python38:
          python.version: '3.8'
        python37:
          python.version: '3.7'
      maxParallel: 8

    steps:
      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: conda update conda --yes
        displayName: Update Conda version

      - bash: |
          conda config --add channels conda-forge
          conda create --yes --name grayskull
        displayName: Create Conda environment (grayskull)

      - bash: |
          conda config --add channels conda-forge
          conda info -a
        displayName: Add Conda-Forge channel

      - bash: |
          source activate grayskull
          conda install --yes python=$PYTHON_VERSION $(grayskull_deps)
          conda install --yes gcc_linux-64 gxx_linux-64 gfortran_linux-64 fortran-compiler numpy
          conda list
        displayName: Installing dependencies

      - bash: |
          source activate grayskull
          pytest tests \
              -vv \
              -n 0 \
              -m "serial" \
              --color=yes \
              --cov=./ \
              --cov-append \
              --cov-report html:coverage-serial-html \
              --cov-report xml:coverage-serial.xml \
              --test-run-title="Linux-py${PYTHON_VERSION}-Serial" \
              --cov-config=$(Build.Repository.LocalPath)/.coveragerc \
              --junit-xml=Linux-py${PYTHON_VERSION}-serial.xml \
              --junit-prefix=Linux-py${PYTHON_VERSION}-serial
        displayName: Running Serial Tests
      - bash: |
          source activate grayskull
          pytest tests \
              -vv \
              -n auto \
              -m "not serial" \
              --color=yes \
              --cov=./ \
              --cov-append \
              --cov-report html:coverage-html \
              --cov-report xml:coverage.xml \
              --test-run-title="Linux-py${PYTHON_VERSION}" \
              --cov-config=$(Build.Repository.LocalPath)/.coveragerc \
              --junit-xml=Linux-py${PYTHON_VERSION}.xml \
              --junit-prefix=Linux-py${PYTHON_VERSION}
        displayName: Running Parallel Tests
      - bash: |
          source activate grayskull
          codecov --token=$(CODECOV_TOKEN)
        displayName: Codecov

  - job:
    displayName: OSX
    pool:
      vmImage: 'macOS-10.14'
    strategy:
      matrix:
        python38:
          python.version: '3.8'
        python37:
          python.version: '3.7'
      maxParallel: 8

    steps:
      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - bash: sudo chown -R $USER $CONDA
        displayName: Take ownership of conda installation (Workaround)

      - bash: conda update conda --yes
        displayName: Update Conda version

      - bash: |
          conda config --add channels conda-forge
          conda create --yes --name grayskull
        displayName: Create Conda environment (grayskull)

      - bash: |
          conda config --add channels conda-forge
          conda info -a
        displayName: Add Conda-Forge channel

      - bash: |
          source activate grayskull
          conda install --yes python=$PYTHON_VERSION $(grayskull_deps)
          conda install --yes clang_osx-64 clangxx_osx-64 gfortran_osx-64 numpy
          conda list
        displayName: Installing dependencies

      - bash: |
          source activate grayskull
          pytest tests \
              -vv \
              -n 0 \
              -m "serial" \
              --color=yes \
              --cov=./ \
              --cov-append \
              --cov-report html:converage-html-serial \
              --cov-report xml:coverage.xml-serial \
              --test-run-title="OSX-py${PYTHON_VERSION}-serial" \
              --cov-config=$(Build.Repository.LocalPath)/.coveragerc \
              --junit-xml=OSX-py${PYTHON_VERSION}-serial.xml \
              --junit-prefix=OSX-py${PYTHON_VERSION}-serial
        displayName: Running Serial Tests
      - bash: |
          source activate grayskull
          pytest tests \
              -vv \
              -n auto \
              -m "not serial" \
              --color=yes \
              --cov=./ \
              --cov-append \
              --cov-report html:converage-html \
              --cov-report xml:coverage.xml \
              --test-run-title="OSX-py${PYTHON_VERSION}" \
              --cov-config=$(Build.Repository.LocalPath)/.coveragerc \
              --junit-xml=OSX-py${PYTHON_VERSION}.xml \
              --junit-prefix=OSX-py${PYTHON_VERSION}
        displayName: Running Parallel Tests
      - bash: |
          source activate grayskull
          codecov --token=$(CODECOV_TOKEN)
        displayName: Codecov

  - job:
    displayName: Windows
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        python38:
          python.version: '3.8'
        python37:
          python.version: '3.7'
      maxParallel: 8

    steps:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH

      - script: conda update conda --yes
        displayName: Update Conda version

      - script: |
          conda config --add channels conda-forge
          conda create --yes --name grayskull
        displayName: Create Conda environment (grayskull)

      - script: |
          conda config --add channels conda-forge
          conda info -a
        displayName: Add Conda-Forge channel

      - script: |
          call activate grayskull
          conda install --yes python=%PYTHON_VERSION% $(grayskull_deps)
          conda install --yes pyopenssl
          conda list
        displayName: Installing dependencies

      - script: |
          call activate grayskull
          pytest tests ^
              -vv ^
              -n 0 ^
              -m "serial" ^
              --color=yes ^
              --cov=./ ^
              --cov-append ^
              --cov-report xml:coverage-serial.xml ^
              --test-run-title="OSX-py%PYTHON_VERSION%-serial" ^
              --cov-config=$(Build.Repository.LocalPath)/.coveragerc ^
              --junit-xml=OSX-py%PYTHON_VERSION%-serial.xml ^
              --junit-prefix=OSX-py%PYTHON_VERSION%-serial
        displayName: Running Serial tests
      - script: |
          call activate grayskull
          pytest tests ^
              -vv ^
              -n auto ^
              -m "not serial" ^
              --color=yes ^
              --cov=./ ^
              --cov-append ^
              --cov-report xml:coverage.xml ^
              --test-run-title="OSX-py%PYTHON_VERSION%" ^
              --cov-config=$(Build.Repository.LocalPath)/.coveragerc ^
              --junit-xml=OSX-py%PYTHON_VERSION%.xml ^
              --junit-prefix=OSX-py%PYTHON_VERSION%
        displayName: Running Parallel tests

      - script: |
          call activate grayskull
          codecov --token=$(CODECOV_TOKEN)
        displayName: Codecov
