name: gs
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-forked
  - pytest-mock
  - requests
  - ruamel.yaml >=0.16.10
  - ruamel.yaml.jinja2
  - stdlib-list
  - pip
  - setuptools >=30.3.0
  - rapidfuzz >=1.9.1
  - progressbar2>=3.53.0
  - colorama
  - mock
  - pytest-console-scripts
  - numpy
  - compilers
  - fortran-compiler
  - conda-souschef >=2.1.1
  - setuptools-scm
  - pkginfo
