name: gs
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.8
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-forked
  - pytest-mock
  - requests
  - stdlib-list
  - pip
  - setuptools >=30.3.0
  - rapidfuzz >=3.0.0
  - progressbar2 >=3.53.0
  - colorama
  - mock
  - pytest-console-scripts
  - numpy
  - compilers
  - fortran-compiler
  - conda-souschef >=2.2.3
  - setuptools-scm
  - pkginfo
  - tomli
  - tomli-w
  - libcblas
  - beautifulsoup4
