# The top-level key is the normalized PyPI name, defined in
# <https://packaging.python.org/en/latest/specifications/name-normalization/>.
# It contains only lowercase, numbers, and dashes, and can be computed via the
# `canonicalize_name` function from `packaging.utils`.

aiohttp-cors:
  conda_forge: aiohttp-cors
  import_name: aiohttp_cors

annoy:
  conda_forge: python-annoy
  import_name: annoy

arrakis:
  conda_forge: arrakis-python
  import_name: arrakis

art:
  conda_forge: ascii-art
  import_name: art

asana:
  conda_forge: python-asana
  import_name: asana

backtrace:
  conda_forge: python-backtrace
  import_name: backtrace

bash-completion:
  conda_forge: py-bash-completion
  import_name: bash_completion

bilby-pipe:
  conda_forge: bilby_pipe
  import_name: bilby_pipe

blis:
  conda_forge: cython-blis
  import_name: blis

boruta:
  conda_forge: boruta_py
  import_name: boruta

build:
  conda_forge: python-build
  import_name: build

captest:
  conda_forge: pvcaptest
  import_name: captest

cdo:
  conda_forge: python-cdo
  import_name: cdo

click-config-file:
  conda_forge: click-config-file
  import_name: click_config_file

cockroachdb:
  conda_forge: cockroachdb-python
  import_name: cockroachdb

conda-lock:
  conda_forge: conda-lock
  import_name: conda_lock

conda-mirror:
  conda_forge: conda-mirror
  import_name: conda_mirror

confluent-kafka:
  conda_forge: python-confluent-kafka
  import_name: confluent_kafka

coreapi:
  conda_forge: python-coreapi
  import_name: coreapi

coreschema:
  conda_forge: python-coreschema
  import_name: coreschema

cryptography-vectors:
  conda_forge: cryptography-vectors
  import_name: cryptography_vectors

cufflinks:
  conda_forge: python-cufflinks
  import_name: cufflinks

dashing:
  conda_forge: python-dashing
  import_name: dashing

dask:
  conda_forge: dask-core
  import_name: dask

data-morph-ai:
  conda_forge: data-morph-ai
  import_name: data_morph

dataclasses:
  conda_forge: dataclasses
  import_name: dataclasses
  avoid_selector: true

datadotworld:
  conda_forge: datadotworld-py
  import_name: datadotworld

datalad-container:
  conda_forge: datalad-container
  import_name: datalad_container

delegator-py:
  conda_forge: delegator
  import_name: delegator

dftd3:
  conda_forge: dftd3-python
  import_name: dftd3

dftd4:
  conda_forge: dftd4-python
  import_name: dftd4

dials-data:
  conda_forge: dials-data
  import_name: dials_data

docker:
  import_name: docker
  conda_forge: docker-py

duckdb:
  import_name: duckdb
  conda_forge: python-duckdb

dye-score:
  conda_forge: dye-score
  import_name: dye_score

eccodes:
  conda_forge: python-eccodes
  import_name: eccodes

empyrical-dist:
  conda_forge: empyrical-dist
  import_name: empyrical_dist

enum34:
  conda_forge: enum34
  import_name: enum
  avoid_selector: true

esprima:
  conda_forge: esprima-python
  import_name: esprima

et-xmlfile:
  conda_forge: et-xmlfile
  import_name: et_xmlfile

evalml:
  conda_forge: evaml-core
  import_name: evalml

exceptiongroup:
  conda_forge: exceptiongroup
  import_name: exceptiongroup
  avoid_selector: true

extract-msg:
  conda_forge: msg-extractor
  import_name: extract_msg

fastjsonschema:
  conda_forge: python-fastjsonschema
  import_name: fastjsonschema

flair:
  conda_forge: python-flair
  import_name: flair

flake8-nb:
  conda_forge: flake8-nb
  import_name: flake8_nb

flask-cors:
  conda_forge: flask_cors
  import_name: flask_cors

flask-json:
  conda_forge: flask_json
  import_name: flask_json

flatbuffers:
  conda_forge: python-flatbuffers
  import_name: flatbuffers

flex:
  conda_forge: flex-swagger
  import_name: flex

flit-core:
  conda_forge: flit-core
  import_name: flit-core

gnupg:
  conda_forge: gnupg-py
  import_name: gnupg

google-cloud-bigquery:
  conda_forge: google-cloud-bigquery-core
  import_name: google.cloud.bigquery

google:
  conda_forge: googlesearch
  import_name: googlesearch

graphviz:
  import_name: graphviz
  conda_forge: python-graphviz

gssapi:
  conda_forge: python-gssapi
  import_name: gssapi

h2o:
  conda_forge: h2o-py
  import_name: h2o

h3:
  conda_forge: h3-py
  import_name: h3

hdfs:
  conda_forge: python-hdfs
  import_name: hdfs

hjson:
  conda_forge: hjson-py
  import_name: hjson

htcondor:
  conda_forge: python-htcondor
  import_name: htcondor

iam-units:
  conda_forge: iam-units
  import_name: iam_units

ib-insync:
  conda_forge: ib-insync
  import_name: ib_insync

import-metadata:
  conda_forge: import_metadata
  import_name: import_metadata
  avoid_selector: true

importlib-metadata:
  conda_forge: importlib-metadata
  import_name: importlib-metadata
  avoid_selector: true

installer:
  conda_forge: python-installer
  import_name: installer

intake-astro:
  conda_forge: intake-accumulo
  import_name: intake_astro

intake-geopandas:
  conda_forge: intake-geopandas
  import_name: intake_geopandas

ioos-tools:
  conda_forge: ioos-tools
  import_name: ioos_tools

jsii:
  conda_forge: python-jsii
  import_name: jsii

jupyter-client:
  conda_forge: jupyter_client
  import_name: jupyter_client

jupyter-jaeger:
  conda_forge: jupyter-jaeger
  import_name: jupyter_jaeger

jupyterlab-git:
  conda_forge: jupyterlab-git
  import_name: jupyterlab_git

jupyterlab-latex:
  conda_forge: jupyterlab-latex
  import_name: jupyterlab_latex

kaleido:
  conda_forge: python-kaleido
  import_name: kaleido

kubernetes:
  conda_forge: python-kubernetes
  import_name: kubernetes

libaio:
  conda_forge: python-libaio
  import_name: libaio

libnacl:
  conda_forge: libnacl-python-bindings
  import_name: libnacl

lmdb:
  conda_forge: python-lmdb
  import_name: lmdb

matplotlib:
  import_name: matplotlib
  conda_forge: matplotlib-base

md-toc:
  conda_forge: md-toc
  import_name: md_toc

message-ix:
  conda_forge: message-ix
  import_name: message_ix

msgpack:
  conda_forge: msgpack-python
  import_name: msgpack

mss:
  conda_forge: python-mss
  import_name: mss

nbconvert-utils:
  conda_forge: nbconvert-utils
  import_name: nbconvert_utils

ndarray-listener:
  conda_forge: ndarray-listener
  import_name: ndarray_listener

neo4j:
  conda_forge: neo4j-python-driver
  import_name: neo4j

neo:
  conda_forge: python-neo
  import_name: neo

nest-asyncio:
  conda_forge: nest-asyncio
  import_name: nest_asyncio

node-semver:
  conda_forge: python-node-semver
  import_name: semver

nvidia-ml-py3:
  conda_forge: nvidia-ml
  import_name: pynvml

opencv-python-headless:
  import_name: cv2
  conda_forge: opencv

opencv-python:
  import_name: cv2
  conda_forge: opencv

ortools:
  conda_forge: ortools-python
  import_name: ortools

p-astro:
  conda_forge: p_astro
  import_name: ligo.p_astro

pandas-flavor:
  conda_forge: pandas-flavor
  import_name: pandas_flavor

paragraph:
  conda_forge: python-paragraph
  import_name: paragraph

prince:
  conda_forge: prince-factor-analysis
  import_name: prince

pvlib:
  conda_forge: pvlib-python
  import_name: pvlib

pyqt4:
  import_name: pyqt4
  conda_forge: pyqt
  delimiter_min: "4.0.0"
  delimiter_max: "5.0.0"

pyqt5:
  import_name: pyqt5
  conda_forge: pyqt
  delimiter_min: "5.0.0"
  delimiter_max: "6.0.0"

pytest-check-links:
  conda_forge: pytest-check-links
  import_name: pytest_check_links

python-datamatrix:
  conda_forge: datamatrix
  import_name: datamatrix

python-fileinspector:
  conda_forge: fileinspector
  import_name: fileinspector

python-opencv:
  import_name: cv2
  conda_forge: opencv

python-pseudorandom:
  conda_forge: pseudorandom
  import_name: pseudorandom

python-pygaze:
  conda_forge: pygaze
  import_name: pygaze

python-qdatamatrix:
  conda_forge: qdatamatrix
  import_name: qdatamatrix

python-qnotifications:
  conda_forge: qnotifications
  import_name: QNotifications

pywin32:
  conda_forge: pywin32-on-windows
  import_name: pywin
  avoid_selector: true

quantum-grove:
  conda_forge: grove
  import_name: grove

radio-beam:
  conda_forge: radio-beam
  import_name: radio_beam

redis:
  conda_forge: redis-py
  import_name: redis

rocketpyalpha:
  conda_forge: rocketpy
  import_name: rocketpy

sage-flatsurf:
  conda_forge: sage-flatsurf
  import_name: flatsurf

sagemaker-inference:
  conda_forge: sagemaker-inference-toolkit
  import_name: sagemaker_inference

sagemaker-mxnet-training:
  conda_forge: sagemaker_mxnet_container
  import_name: sagemaker_mxnet_container

scikit-build:
  conda_forge: scikit-build
  import_name: skbuild

scikit-learn:
  conda_forge: scikit-learn
  import_name: sklearn

setuptools-scm:
  conda_forge: setuptools-scm
  import_name: setuptools_scm

sounddevice:
  conda_forge: python-sounddevice
  import_name: sounddevice

soundfile:
  conda_forge: pysoundfile
  import_name: soundfile

spherical-functions:
  conda_forge: spherical_functions
  import_name: spherical_functions

sphinx-rtd-theme:
  conda_forge: sphinx_rtd_theme
  import_name: sphinx_rtd_theme

stjudecloud-oliver:
  conda_forge: oliver
  import_name: oliver

symengine:
  conda_forge: python-symengine
  import_name: symengine

systemd-python:
  conda_forge: python-systemd
  import_name: systemd

tables:
  import_name: pytables
  conda_forge: pytables

tblite:
  conda_forge: tblite-python
  import_name: tblite

termstyle:
  conda_forge: python-termstyle
  import_name: termstyle

torch-cluster:
  conda_forge: pytorch_cluster
  import_name: torch_cluster

torch-geometric:
  conda_forge: pytorch_geometric
  import_name: torch_geometric

torch-sparse:
  conda_forge: pytorch_sparse
  import_name: torch_sparse

torch:
  conda_forge: pytorch
  import_name: torch

trino:
  conda_forge: trino-python-client
  import_name: trino

typing-extensions:
  conda_forge: typing_extensions
  import_name: typing_extensions
  avoid_selector: true

typing:
  conda_forge: typing
  import_name: typing
  avoid_selector: true

usedave:
  conda_forge: dave
  import_name: numpy

vsts:
  conda_forge: vsts-python-api
  import_name: vsts

xtb:
  conda_forge: xtb-python
  import_name: xtb

xxhash:
  import_name: xxhash
  conda_forge: python-xxhash
